### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by MysticDakra**

### CODE REVIEW

**Comment by MysticDakra** [comment]
test

**Review by egweber2 — APPROVED** [review]
LGTM

Just a thought -- I like including "Business Problem" as a prompt. Forcing a description of "why" we're doing something often leads to better problem solving.

**Comment by MysticDakra** [comment]
I like this! For which one do you think?  or for both @egweber2

**Comment by MysticDakra** [comment]
Does this still leave notifications?

**Pull request merged**
